# Generated by Django 4.2.5 on 2023-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActividadEnseñanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaGenerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('URL', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('horasTeoria', models.IntegerField()),
                ('horasPractica', models.IntegerField()),
                ('portafolioEvidencia', models.BooleanField(default=False)),
                ('actividadAprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tema.actividadaprendizaje')),
                ('actividadEnseñanza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tema.actividadenseñanza')),
                ('competenciaGenerica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tema.competenciagenerica')),
                ('instrumentoEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tema.instrumentoevaluacion')),
            ],
        ),
    ]
