# Generated by Django 4.2.5 on 2023-09-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carrera', '0001_initial'),
        ('Maestro', '0004_alter_maestro_tipoestudios'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntencionDidactica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('clave', models.CharField(max_length=32)),
                ('creditosTeoricos', models.IntegerField()),
                ('creditosPracticos', models.IntegerField()),
                ('competenciaGeneral', models.TextField()),
                ('caracterizacion', models.TextField()),
                ('tipoMateria', models.CharField(choices=[('O', 'Especialidad'), ('C', 'Comun')], max_length=32)),
                ('semestre', models.IntegerField()),
                ('carerra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Carrera.carrera')),
                ('intencionDidactica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Materia.intenciondidactica')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.maestro')),
            ],
        ),
    ]
