# Generated by Django 4.2.5 on 2023-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clase', '__first__'),
        ('Tema', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('matricula', models.CharField(max_length=16)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoTemaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('evidencia', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Alumno.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.clase')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tema.tema')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Alumno.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.clase')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumnoClase',
            field=models.ManyToManyField(related_name='alumnos_clases', through='Alumno.AlumnoClase', to='Clase.clase'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumnoTemaClase',
            field=models.ManyToManyField(related_name='alumnos_temas_clases', through='Alumno.AlumnoTemaClase', to='Clase.clase'),
        ),
    ]
