# Generated by Django 4.2.5 on 2023-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materia', '__first__'),
        ('Maestro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('año', models.IntegerField()),
                ('semestre', models.CharField(choices=[('1', 'Enero-Mayo'), ('2', 'Verano'), ('3', 'Agosto-Diciembre')], max_length=32)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Materia.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.aula')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.grupo')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.maestro')),
            ],
        ),
    ]
