# Generated by Django 4.2.5 on 2023-09-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tema', '0001_initial'),
        ('Materia', '0001_initial'),
        ('Maestro', '0004_alter_maestro_tipoestudios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('matricula', models.CharField(max_length=16)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('año', models.IntegerField()),
                ('semestre', models.CharField(choices=[('1', 'Enero-Mayo'), ('2', 'Verano'), ('3', 'Agosto-Diciembre')], max_length=32)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Materia.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.aula')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.grupo')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Maestro.maestro')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoTemaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('evidencia', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.clase')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tema.tema')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clase.clase')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumnoClase',
            field=models.ManyToManyField(related_name='alumnos_clases', through='Clase.AlumnoClase', to='Clase.clase'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumnoTemaClase',
            field=models.ManyToManyField(related_name='alumnos_temas_clases', through='Clase.AlumnoTemaClase', to='Clase.clase'),
        ),
    ]
