# Generated by Django 4.2.5 on 2023-09-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnoclase',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='alumnoclase',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='alumnotemaclase',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='alumnotemaclase',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='alumnotemaclase',
            name='tema',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='AlumnoClase',
        ),
        migrations.DeleteModel(
            name='AlumnoTemaClase',
        ),
    ]
