# Generated by Django 4.2.5 on 2023-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
