# Generated by Django 4.2.5 on 2023-11-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Competencia', '__first__'),
        ('Tema', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Competencia.competencia')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tema.tema')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioDesempeño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('meta', models.TextField()),
                ('indicadores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AtributoEgreso.indicador')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteriosDesempeño', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AtributoEgreso.criteriodesempeño')),
            ],
        ),
    ]
