# Generated by Django 4.2.5 on 2023-09-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellido', models.CharField(max_length=128)),
                ('estudios', models.CharField(max_length=256)),
                ('tipoEstudios', models.CharField(max_length=128)),
                ('fechaIngrso', models.DateField()),
                ('puesto', models.CharField(max_length=256)),
            ],
        ),
    ]
