# Generated by Django 4.2.5 on 2023-09-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='tipoEstudios',
            field=models.CharField(choices=[('1', 'Licenciatura'), ('2', 'Maestria'), ('3', 'Doctorado'), ('4', 'Post Doctorado')], max_length=128),
        ),
    ]
