# Generated by Django 4.2.5 on 2023-09-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Alumnos',
        ),
    ]
