# Generated by Django 4.2.5 on 2023-09-28 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materia', '0001_initial'),
        ('Tema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('nivel', models.CharField(choices=[('I', 'Introductorio'), ('M', 'Medio'), ('A', 'Avanzado')], max_length=32)),
                ('resumen', models.TextField()),
                ('temas', models.ManyToManyField(to='Tema.tema')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCompetencia', models.CharField(choices=[('1', 'Ingreso'), ('2', 'Egreso')], max_length=32)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Competencia.competencia')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Materia.materia')),
            ],
        ),
    ]
